// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: squad/liquidfarming/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the liquidfarming module's genesis state.
type GenesisState struct {
	Params               Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	LiquidFarms          []LiquidFarm          `protobuf:"bytes,2,rep,name=liquid_farms,json=liquidFarms,proto3" json:"liquid_farms"`
	QueuedFarmingRecords []QueuedFarmingRecord `protobuf:"bytes,3,rep,name=queued_farming_records,json=queuedFarmingRecords,proto3" json:"queued_farming_records"`
	RewardsAuctions      []RewardsAuction      `protobuf:"bytes,4,rep,name=rewards_auctions,json=rewardsAuctions,proto3" json:"rewards_auctions"`
	Bids                 []Bid                 `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids"`
	WinningBidRecords    []WinningBidRecord    `protobuf:"bytes,6,rep,name=winning_bid_records,json=winningBidRecords,proto3" json:"winning_bid_records"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f9cf71ffd184b0, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// QueuedFarmingRecord defines a custom queued farming record that is required to be recorded
// in genesis state.
type QueuedFarmingRecord struct {
	EndTime          time.Time     `protobuf:"bytes,1,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
	FarmingCoinDenom string        `protobuf:"bytes,2,opt,name=farming_coin_denom,json=farmingCoinDenom,proto3" json:"farming_coin_denom,omitempty"`
	Farmer           string        `protobuf:"bytes,3,opt,name=farmer,proto3" json:"farmer,omitempty"`
	QueuedFarming    QueuedFarming `protobuf:"bytes,4,opt,name=queued_farming,json=queuedFarming,proto3" json:"queued_farming"`
}

func (m *QueuedFarmingRecord) Reset()         { *m = QueuedFarmingRecord{} }
func (m *QueuedFarmingRecord) String() string { return proto.CompactTextString(m) }
func (*QueuedFarmingRecord) ProtoMessage()    {}
func (*QueuedFarmingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f9cf71ffd184b0, []int{1}
}
func (m *QueuedFarmingRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedFarmingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedFarmingRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedFarmingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedFarmingRecord.Merge(m, src)
}
func (m *QueuedFarmingRecord) XXX_Size() int {
	return m.Size()
}
func (m *QueuedFarmingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedFarmingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedFarmingRecord proto.InternalMessageInfo

// WinningBidRecord defines a custom winning bid record that is required to be recorded
// in genesis state.
type WinningBidRecord struct {
	AuctionId  uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	WinningBid Bid    `protobuf:"bytes,2,opt,name=winning_bid,json=winningBid,proto3" json:"winning_bid"`
}

func (m *WinningBidRecord) Reset()         { *m = WinningBidRecord{} }
func (m *WinningBidRecord) String() string { return proto.CompactTextString(m) }
func (*WinningBidRecord) ProtoMessage()    {}
func (*WinningBidRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f9cf71ffd184b0, []int{2}
}
func (m *WinningBidRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WinningBidRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WinningBidRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WinningBidRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinningBidRecord.Merge(m, src)
}
func (m *WinningBidRecord) XXX_Size() int {
	return m.Size()
}
func (m *WinningBidRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WinningBidRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WinningBidRecord proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "squad.liquidfarming.v1beta1.GenesisState")
	proto.RegisterType((*QueuedFarmingRecord)(nil), "squad.liquidfarming.v1beta1.QueuedFarmingRecord")
	proto.RegisterType((*WinningBidRecord)(nil), "squad.liquidfarming.v1beta1.WinningBidRecord")
}

func init() {
	proto.RegisterFile("squad/liquidfarming/v1beta1/genesis.proto", fileDescriptor_90f9cf71ffd184b0)
}

var fileDescriptor_90f9cf71ffd184b0 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x3f, 0x6f, 0xd3, 0x40,
	0x1c, 0xb5, 0x1b, 0x13, 0xd2, 0x4b, 0x81, 0x70, 0xad, 0x2a, 0x2b, 0x08, 0x27, 0x2a, 0x03, 0xe1,
	0x4f, 0x6d, 0x5a, 0x24, 0x86, 0x2e, 0xa8, 0x01, 0xb5, 0x42, 0x62, 0x08, 0x06, 0xa9, 0x12, 0x42,
	0xb2, 0xce, 0xbe, 0xab, 0x39, 0x29, 0xbe, 0x4b, 0x7c, 0x36, 0x81, 0x9d, 0x81, 0xb1, 0x33, 0x53,
	0x3f, 0x4e, 0xc7, 0x8e, 0x4c, 0x80, 0x92, 0x85, 0x6f, 0x01, 0xf2, 0xdd, 0xa5, 0xad, 0x43, 0x65,
	0x75, 0xb3, 0x9f, 0xdf, 0x7b, 0xbf, 0xbb, 0xf7, 0x7b, 0x32, 0x78, 0x20, 0xc6, 0x39, 0xc2, 0xde,
	0x90, 0x8e, 0x73, 0x8a, 0x0f, 0x51, 0x9a, 0x50, 0x16, 0x7b, 0x9f, 0xb6, 0x42, 0x92, 0xa1, 0x2d,
	0x2f, 0x26, 0x8c, 0x08, 0x2a, 0xdc, 0x51, 0xca, 0x33, 0x0e, 0xef, 0x48, 0xaa, 0x5b, 0xa2, 0xba,
	0x9a, 0xda, 0x5e, 0x8b, 0x79, 0xcc, 0x25, 0xcf, 0x2b, 0x9e, 0x94, 0xa4, 0xdd, 0x89, 0x39, 0x8f,
	0x87, 0xc4, 0x93, 0x6f, 0x61, 0x7e, 0xe8, 0x65, 0x34, 0x21, 0x22, 0x43, 0xc9, 0x48, 0x13, 0xbc,
	0xaa, 0xf1, 0xe5, 0x49, 0x4a, 0xd0, 0xab, 0x12, 0x8c, 0x50, 0x8a, 0x12, 0x7d, 0xdc, 0x8d, 0xef,
	0x16, 0x58, 0xd9, 0x57, 0x17, 0x78, 0x9b, 0xa1, 0x8c, 0xc0, 0x5d, 0x50, 0x57, 0x04, 0xdb, 0xec,
	0x9a, 0xbd, 0xe6, 0xf6, 0x3d, 0xb7, 0xe2, 0x42, 0xee, 0x40, 0x52, 0xfb, 0xd6, 0xc9, 0xcf, 0x8e,
	0xe1, 0x6b, 0x21, 0x1c, 0x80, 0x15, 0xc5, 0x0e, 0x0a, 0xba, 0xb0, 0x97, 0xba, 0xb5, 0x5e, 0x73,
	0xfb, 0x7e, 0xa5, 0xd1, 0x6b, 0x89, 0xee, 0xa1, 0x34, 0xd1, 0x66, 0xcd, 0xe1, 0x19, 0x22, 0xe0,
	0x10, 0xac, 0x8f, 0x73, 0x92, 0x13, 0xe5, 0x48, 0x59, 0x1c, 0xa4, 0x24, 0xe2, 0x29, 0x16, 0x76,
	0x4d, 0x7a, 0x3f, 0xa9, 0xf4, 0x7e, 0x23, 0xa5, 0x7b, 0x0a, 0xf5, 0xa5, 0x50, 0x0f, 0x59, 0x1b,
	0xff, 0xff, 0x49, 0xc0, 0x0f, 0xa0, 0x95, 0x92, 0x09, 0x4a, 0xb1, 0x08, 0x50, 0x1e, 0x65, 0x94,
	0x33, 0x61, 0x5b, 0x72, 0xce, 0xa3, 0xca, 0x39, 0xbe, 0x12, 0xed, 0x2a, 0x8d, 0x1e, 0x71, 0x2b,
	0x2d, 0xa1, 0x02, 0xee, 0x00, 0x2b, 0xa4, 0x58, 0xd8, 0xd7, 0xa4, 0x63, 0xb7, 0xd2, 0xb1, 0x4f,
	0xe7, 0x27, 0x95, 0x1a, 0x18, 0x81, 0xd5, 0x09, 0x65, 0xac, 0x08, 0x20, 0xa4, 0xf8, 0x2c, 0x84,
	0xba, 0xb4, 0xda, 0xac, 0xb4, 0x3a, 0x50, 0xba, 0x3e, 0xc5, 0xa5, 0x04, 0x6e, 0x4f, 0x16, 0x70,
	0xb1, 0xd3, 0xf8, 0x76, 0xdc, 0x31, 0xfe, 0x1c, 0x77, 0x8c, 0x8d, 0xbf, 0x26, 0x58, 0xbd, 0x24,
	0x3c, 0xf8, 0x1c, 0x34, 0x08, 0xc3, 0x41, 0x51, 0x53, 0xdd, 0x92, 0xb6, 0xab, 0x3a, 0xec, 0xce,
	0x3b, 0xec, 0xbe, 0x9b, 0x77, 0xb8, 0xdf, 0x28, 0x06, 0x1d, 0xfd, 0xea, 0x98, 0xfe, 0x75, 0xc2,
	0x70, 0x81, 0xc3, 0xc7, 0x00, 0xce, 0x17, 0x19, 0x71, 0xca, 0x02, 0x4c, 0x18, 0x4f, 0xec, 0xa5,
	0xae, 0xd9, 0x5b, 0xf6, 0x5b, 0xfa, 0xcb, 0x0b, 0x4e, 0xd9, 0xcb, 0x02, 0x87, 0xeb, 0xa0, 0x5e,
	0x60, 0x24, 0xb5, 0x6b, 0x92, 0xa1, 0xdf, 0xe0, 0x01, 0xb8, 0x59, 0x6e, 0x85, 0x6d, 0xc9, 0xc3,
	0x3c, 0xbc, 0x7a, 0x1b, 0x74, 0x0a, 0x37, 0x4a, 0x3d, 0xb8, 0x90, 0xc0, 0x57, 0x13, 0xb4, 0x16,
	0x93, 0x83, 0x77, 0x01, 0xd0, 0xbd, 0x08, 0x28, 0x96, 0x01, 0x58, 0xfe, 0xb2, 0x46, 0x5e, 0x61,
	0xb8, 0x0f, 0x9a, 0x17, 0x96, 0x24, 0x6f, 0x75, 0xf5, 0x3d, 0x83, 0xf3, 0x7d, 0x9c, 0x1f, 0xa3,
	0x3f, 0x38, 0x99, 0x3a, 0xe6, 0xe9, 0xd4, 0x31, 0x7f, 0x4f, 0x1d, 0xf3, 0x68, 0xe6, 0x18, 0xa7,
	0x33, 0xc7, 0xf8, 0x31, 0x73, 0x8c, 0xf7, 0xcf, 0x62, 0x9a, 0x7d, 0xcc, 0x43, 0x37, 0xe2, 0x89,
	0x17, 0x71, 0x91, 0x70, 0x39, 0x66, 0x73, 0x88, 0x42, 0xa1, 0xff, 0x1a, 0x9f, 0x17, 0x7e, 0x03,
	0xd9, 0x97, 0x11, 0x11, 0x61, 0x5d, 0x2e, 0xea, 0xe9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x90, 0xae, 0x8b, 0xda, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WinningBidRecords) > 0 {
		for iNdEx := len(m.WinningBidRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WinningBidRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Bids) > 0 {
		for iNdEx := len(m.Bids) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bids[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RewardsAuctions) > 0 {
		for iNdEx := len(m.RewardsAuctions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardsAuctions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.QueuedFarmingRecords) > 0 {
		for iNdEx := len(m.QueuedFarmingRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QueuedFarmingRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.LiquidFarms) > 0 {
		for iNdEx := len(m.LiquidFarms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidFarms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueuedFarmingRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedFarmingRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedFarmingRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.QueuedFarming.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Farmer) > 0 {
		i -= len(m.Farmer)
		copy(dAtA[i:], m.Farmer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Farmer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FarmingCoinDenom) > 0 {
		i -= len(m.FarmingCoinDenom)
		copy(dAtA[i:], m.FarmingCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.FarmingCoinDenom)))
		i--
		dAtA[i] = 0x12
	}
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintGenesis(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *WinningBidRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WinningBidRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WinningBidRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WinningBid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AuctionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.LiquidFarms) > 0 {
		for _, e := range m.LiquidFarms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.QueuedFarmingRecords) > 0 {
		for _, e := range m.QueuedFarmingRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardsAuctions) > 0 {
		for _, e := range m.RewardsAuctions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Bids) > 0 {
		for _, e := range m.Bids {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WinningBidRecords) > 0 {
		for _, e := range m.WinningBidRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *QueuedFarmingRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.FarmingCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Farmer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.QueuedFarming.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *WinningBidRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovGenesis(uint64(m.AuctionId))
	}
	l = m.WinningBid.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidFarms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidFarms = append(m.LiquidFarms, LiquidFarm{})
			if err := m.LiquidFarms[len(m.LiquidFarms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedFarmingRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueuedFarmingRecords = append(m.QueuedFarmingRecords, QueuedFarmingRecord{})
			if err := m.QueuedFarmingRecords[len(m.QueuedFarmingRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsAuctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardsAuctions = append(m.RewardsAuctions, RewardsAuction{})
			if err := m.RewardsAuctions[len(m.RewardsAuctions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bids = append(m.Bids, Bid{})
			if err := m.Bids[len(m.Bids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinningBidRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WinningBidRecords = append(m.WinningBidRecords, WinningBidRecord{})
			if err := m.WinningBidRecords[len(m.WinningBidRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedFarmingRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedFarmingRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedFarmingRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FarmingCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FarmingCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Farmer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Farmer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedFarming", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QueuedFarming.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WinningBidRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WinningBidRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WinningBidRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinningBid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WinningBid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
